spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: create-drop